name: Build, publish and deploy to MonsterASP.NET
on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
          
      - name: Install dependencies
        run: dotnet restore Oqtane.sln
        
      - name: Build
        run: dotnet build Oqtane.Database.MySQL --configuration Release --no-restore --output ./publish --runtime win-x86 
      - name: Build2
        run: dotnet build Oqtane.Database.PostgreSQL --configuration Release --no-restore --output ./publish --runtime win-x86
      - name: Build3
        run: dotnet build Oqtane.Database.Sqlite --configuration Release --no-restore --output ./publish --runtime win-x86
      - name: Build4
        run: dotnet build Oqtane.Database.SqlServer --configuration Release --no-restore --output ./publish --runtime win-x86

      - name: Publish
        run: dotnet publish ./Oqtane.Server/Oqtane.Server.csproj --configuration Release --output ./publish --runtime win-x86 
        
      - name: Test with .NET
        run: dotnet test

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
